import { Tag } from "@/types";

export const tags: Tag[] = [
  { value: "javascript", label: "javascript" },
  { value: "python", label: "python" },
  { value: "java", label: "java" },
  { value: "c#", label: "c#" },
  { value: "php", label: "php" },
  { value: "html", label: "html" },
  { value: "css", label: "css" },
  { value: "reactjs", label: "reactjs" },
  { value: "angular", label: "angular" },
  { value: "node.js", label: "node.js" },
  { value: "ruby-on-rails", label: "ruby-on-rails" },
  { value: "django", label: "django" },
  { value: "express", label: "express" },
  { value: "vue.js", label: "vue.js" },
  { value: "typescript", label: "typescript" },
  { value: "android", label: "android" },
  { value: "ios", label: "ios" },
  { value: "swift", label: "swift" },
  { value: "kotlin", label: "kotlin" },
  { value: "flutter", label: "flutter" },
  { value: "firebase", label: "firebase" },
  { value: "aws", label: "aws" },
  { value: "docker", label: "docker" },
  { value: "kubernetes", label: "kubernetes" },
  { value: "git", label: "git" },
  { value: "github", label: "github" },
  { value: "sql", label: "sql" },
  { value: "mysql", label: "mysql" },
  { value: "postgresql", label: "postgresql" },
  { value: "mongodb", label: "mongodb" },
  { value: "rest", label: "rest" },
  { value: "graphql", label: "graphql" },
  { value: "api", label: "api" },
  { value: "json", label: "json" },
  { value: "xml", label: "xml" },
  { value: "npm", label: "npm" },
  { value: "yarn", label: "yarn" },
  { value: "webpack", label: "webpack" },
  { value: "gulp", label: "gulp" },
  { value: "babel", label: "babel" },
  { value: "sass", label: "sass" },
  { value: "less", label: "less" },
  { value: "css3", label: "css3" },
  { value: "html5", label: "html5" },
  { value: "responsive-design", label: "responsive-design" },
  { value: "design-patterns", label: "design-patterns" },
  { value: "algorithm", label: "algorithm" },
  { value: "data-structures", label: "data-structures" },
  { value: "testing", label: "testing" },
  { value: "unit-testing", label: "unit-testing" },
  { value: "integration-testing", label: "integration-testing" },
  { value: "continuous-integration", label: "continuous-integration" },
  { value: "agile", label: "agile" },
  { value: "scrum", label: "scrum" },
  { value: "kanban", label: "kanban" },
  { value: "devops", label: "devops" },
  { value: "docker-compose", label: "docker-compose" },
  { value: "linux", label: "linux" },
  { value: "bash", label: "bash" },
  { value: "shell", label: "shell" },
  { value: "windows", label: "windows" },
  { value: "macos", label: "macos" },
  { value: "version-control", label: "version-control" },
  { value: "agile", label: "agile" },
  { value: "scrum", label: "scrum" },
  { value: "kanban", label: "kanban" },
  { value: "devops", label: "devops" },
  { value: "linux", label: "linux" },
  { value: "bash", label: "bash" },
  { value: "shell", label: "shell" },
  { value: "windows", label: "windows" },
  { value: "macos", label: "macos" },
  { value: "git", label: "git" },
  { value: "svn", label: "svn" },
  { value: "mercurial", label: "mercurial" },
  { value: "perforce", label: "perforce" },
  { value: "agile-methodology", label: "agile-methodology" },
  { value: "waterfall", label: "waterfall" },
  { value: "pm2", label: "pm2" },
  { value: "npm-scripts", label: "npm-scripts" },
  { value: "webpack-config", label: "webpack-config" },
  { value: "eslint", label: "eslint" },
  { value: "prettier", label: "prettier" },
  { value: "babel", label: "babel" },
  { value: "webpack-plugins", label: "webpack-plugins" },
  { value: "webpack-loaders", label: "webpack-loaders" },
  { value: "webpack-dev-server", label: "webpack-dev-server" },
  { value: "redux", label: "redux" },
  { value: "mobx", label: "mobx" },
  { value: "ngrx", label: "ngrx" },
  { value: "rxjs", label: "rxjs" },
  { value: "state-management", label: "state-management" },
  { value: "design-patterns", label: "design-patterns" },
  { value: "solid-principles", label: "solid-principles" },
  { value: "oop", label: "oop" },
  { value: "functional-programming", label: "functional-programming" },
  { value: "react-hooks", label: "react-hooks" },
  { value: "custom-hooks", label: "custom-hooks" },
  { value: "jest", label: "jest" },
  { value: "mocha", label: "mocha" },
  { value: "chai", label: "chai" },
  { value: "cypress", label: "cypress" },
  { value: "selenium", label: "selenium" },
  { value: "puppeteer", label: "puppeteer" },
  { value: "enzyme", label: "enzyme" },
  { value: "storybook", label: "storybook" },
  { value: "tailwindcss", label: "tailwindcss" },
  { value: "material-ui", label: "material-ui" },
  { value: "ant-design", label: "ant-design" },
  { value: "bootstrap", label: "bootstrap" },
  { value: "foundation", label: "foundation" },
  { value: "bulma", label: "bulma" },
  { value: "chakra-ui", label: "chakra-ui" },
  { value: "svelte", label: "svelte" },
  { value: "next.js", label: "next.js" },
  { value: "nuxt.js", label: "nuxt.js" },
  { value: "gatsby", label: "gatsby" },
  { value: "blazor", label: "blazor" },
  { value: "dotnet-core", label: "dotnet-core" },
  { value: "razor", label: "razor" },
  { value: "wpf", label: "wpf" },
  { value: "winforms", label: "winforms" },
  { value: "asp.net", label: "asp.net" },
  { value: "spring-boot", label: "spring-boot" },
  { value: "hibernate", label: "hibernate" },
  { value: "jpa", label: "jpa" },
  { value: "micronaut", label: "micronaut" },
  { value: "quarkus", label: "quarkus" },
  { value: "play-framework", label: "play-framework" },
  { value: "lagom", label: "lagom" },
  { value: "akka", label: "akka" },
  { value: "vert.x", label: "vert.x" },
  { value: "ratpack", label: "ratpack" },
  { value: "dropwizard", label: "dropwizard" },
  { value: "kafka", label: "kafka" },
  { value: "rabbitmq", label: "rabbitmq" },
  { value: "activemq", label: "activemq" },
  { value: "redis", label: "redis" },
  { value: "memcached", label: "memcached" },
  { value: "neo4j", label: "neo4j" },
  { value: "cassandra", label: "cassandra" },
  { value: "elasticsearch", label: "elasticsearch" },
  { value: "solr", label: "solr" },
  { value: "logstash", label: "logstash" },
  { value: "filebeat", label: "filebeat" },
  { value: "metricbeat", label: "metricbeat" },
  { value: "kibana", label: "kibana" },
  { value: "grafana", label: "grafana" },
  { value: "prometheus", label: "prometheus" },
  { value: "new-relic", label: "new-relic" },
  { value: "datadog", label: "datadog" },
  { value: "zabbix", label: "zabbix" },
  { value: "nagios", label: "nagios" },
  { value: "consul", label: "consul" },
  { value: "vault", label: "vault" },
  { value: "terraform", label: "terraform" },
  { value: "ansible", label: "ansible" },
  { value: "chef", label: "chef" },
  { value: "puppet", label: "puppet" },
  { value: "saltstack", label: "saltstack" },
  { value: "jenkins", label: "jenkins" },
  { value: "circleci", label: "circleci" },
  { value: "travis-ci", label: "travis-ci" },
  { value: "github-actions", label: "github-actions" },
  { value: "gitlab-ci", label: "gitlab-ci" },
  { value: "bitbucket-pipelines", label: "bitbucket-pipelines" },
  { value: "azure-devops", label: "azure-devops" },
  { value: "cross-browser-testing", label: "cross-browser-testing" },
  { value: "load-testing", label: "load-testing" },
  { value: "stress-testing", label: "stress-testing" },
  { value: "performance-testing", label: "performance-testing" },
  { value: "usability-testing", label: "usability-testing" },
  { value: "accessibility-testing", label: "accessibility-testing" },
  { value: "security-testing", label: "security-testing" },
  { value: "penetration-testing", label: "penetration-testing" },
  { value: "vulnerability-scanning", label: "vulnerability-scanning" },
  { value: "threat-modeling", label: "threat-modeling" },
  { value: "cybersecurity", label: "cybersecurity" },
  { value: "network-security", label: "network-security" },
  { value: "application-security", label: "application-security" },
  { value: "database-security", label: "database-security" },
  { value: "cloud-security", label: "cloud-security" },
  { value: "ethical-hacking", label: "ethical-hacking" },
  { value: "reverse-engineering", label: "reverse-engineering" },
  { value: "cryptography", label: "cryptography" },
  { value: "blockchain", label: "blockchain" },
  { value: "ethereum", label: "ethereum" },
  { value: "bitcoin", label: "bitcoin" },
  { value: "smart-contracts", label: "smart-contracts" },
  { value: "solidity", label: "solidity" },
  { value: "web3.js", label: "web3.js" },
  { value: "decentralized-apps", label: "decentralized-apps" },
  { value: "dapps", label: "dapps" },
  { value: "ipfs", label: "ipfs" },
  { value: "filecoin", label: "filecoin" },
  { value: "hyperledger", label: "hyperledger" },
  { value: "nft", label: "nft" },
  { value: "defi", label: "defi" },
  { value: "staking", label: "staking" },
  { value: "yield-farming", label: "yield-farming" },
  { value: "liquidity-pools", label: "liquidity-pools" },
  { value: "stablecoins", label: "stablecoins" },
  { value: "tokenomics", label: "tokenomics" },
  { value: "web-assembly", label: "web-assembly" },
  { value: "wasm", label: "wasm" },
  { value: "assemblyscript", label: "assemblyscript" },
  { value: "rust", label: "rust" },
  { value: "go", label: "go" },
  { value: "haskell", label: "haskell" },
  { value: "elm", label: "elm" },
  { value: "clojure", label: "clojure" },
  { value: "erlang", label: "erlang" },
  { value: "elixir", label: "elixir" },
  { value: "crystal", label: "crystal" },
  { value: "f#", label: "f#" },
  { value: "ocaml", label: "ocaml" },
  { value: "r", label: "r" },
  { value: "matlab", label: "matlab" },
  { value: "sas", label: "sas" },
  { value: "julia", label: "julia" },
  { value: "groovy", label: "groovy" },
  { value: "lua", label: "lua" },
  { value: "tcl", label: "tcl" },
  { value: "perl", label: "perl" },
  { value: "embedded-systems", label: "embedded-systems" },
  { value: "arduino", label: "arduino" },
  { value: "raspberry-pi", label: "raspberry-pi" },
  { value: "iot", label: "iot" },
  { value: "robotics", label: "robotics" },
  { value: "automation", label: "automation" },
  { value: "control-systems", label: "control-systems" },
  { value: "mechatronics", label: "mechatronics" },
  { value: "industrial-automation", label: "industrial-automation" },
  { value: "smart-home", label: "smart-home" },
  { value: "wearable-technology", label: "wearable-technology" },
  { value: "biotechnology", label: "biotechnology" },
  { value: "genomics", label: "genomics" },
  { value: "bioinformatics", label: "bioinformatics" },
  { value: "computational-biology", label: "computational-biology" },
  { value: "chemoinformatics", label: "chemoinformatics" },
  { value: "medical-imaging", label: "medical-imaging" },
  { value: "health-informatics", label: "health-informatics" },
  { value: "e-health", label: "e-health" },
  { value: "telemedicine", label: "telemedicine" },
  { value: "smart-cities", label: "smart-cities" },
  { value: "urban-informatics", label: "urban-informatics" },
  {
    value: "geographic-information-system",
    label: "geographic-information-system",
  },
  { value: "gis", label: "gis" },
  { value: "remote-sensing", label: "remote-sensing" },
  { value: "satellite-imagery", label: "satellite-imagery" },
  { value: "climate-modeling", label: "climate-modeling" },
  { value: "weather-forecasting", label: "weather-forecasting" },
  { value: "cognitive-science", label: "cognitive-science" },
  { value: "artificial-intelligence", label: "artificial-intelligence" },
  { value: "machine-learning", label: "machine-learning" },
  { value: "deep-learning", label: "deep-learning" },
  { value: "neural-networks", label: "neural-networks" },
  { value: "computer-vision", label: "computer-vision" },
  {
    value: "natural-language-processing",
    label: "natural-language-processing",
  },
  { value: "speech-recognition", label: "speech-recognition" },
  { value: "image-processing", label: "image-processing" },
  { value: "signal-processing", label: "signal-processing" },
  { value: "pattern-recognition", label: "pattern-recognition" },
  { value: "data-science", label: "data-science" },
  { value: "big-data", label: "big-data" },
  { value: "data-analytics", label: "data-analytics" },
  { value: "business-intelligence", label: "business-intelligence" },
  { value: "data-mining", label: "data-mining" },
  { value: "data-warehousing", label: "data-warehousing" },
  { value: "data-visualization", label: "data-visualization" },
  { value: "data-pipeline", label: "data-pipeline" },
  { value: "data-lake", label: "data-lake" },
  { value: "data-governance", label: "data-governance" },
  { value: "data-quality", label: "data-quality" },
  { value: "hipaa", label: "hipaa" },
  { value: "incident-management", label: "incident-management" },
  { value: "business-continuity", label: "business-continuity" },
  { value: "disaster-recovery", label: "disaster-recovery" },
  { value: "risk-management", label: "risk-management" },
  { value: "compliance", label: "compliance" },
  { value: "audit", label: "audit" },
  { value: "governance", label: "governance" },
  { value: "board-of-directors", label: "board-of-directors" },
  { value: "executive-leadership", label: "executive-leadership" },
  { value: "corporate-strategy", label: "corporate-strategy" },
  { value: "mergers-and-acquisitions", label: "mergers-and-acquisitions" },
  { value: "divestitures", label: "divestitures" },
  { value: "spinoffs", label: "spinoffs" },
  { value: "ipo", label: "ipo" },
  { value: "initial-public-offering", label: "initial-public-offering" },
  { value: "stock-market", label: "stock-market" },
  { value: "investment-banking", label: "investment-banking" },
  { value: "private-equity", label: "private-equity" },
  { value: "venture-capital", label: "venture-capital" },
  { value: "angel-investing", label: "angel-investing" },
  { value: "crowdfunding", label: "crowdfunding" },
  { value: "startups", label: "startups" },
  { value: "entrepreneurship", label: "entrepreneurship" },
  { value: "innovation", label: "innovation" },
  { value: "product-management", label: "product-management" },
  { value: "product-development", label: "product-development" },
  { value: "product-design", label: "product-design" },
  { value: "interaction-design", label: "interaction-design" },
  { value: "visual-design", label: "visual-design" },
  { value: "graphic-design", label: "graphic-design" },
  { value: "branding", label: "branding" },
  { value: "marketing", label: "marketing" },
  { value: "digital-marketing", label: "digital-marketing" },
  { value: "content-marketing", label: "content-marketing" },
  { value: "seo", label: "seo" },
  { value: "agile", label: "agile" },
  { value: "scrum", label: "scrum" },
  { value: "kanban", label: "kanban" },
  { value: "lean", label: "lean" },
  { value: "six-sigma", label: "six-sigma" },
];

export const techSkills: string[] = [
  "Problem Solving",
  "Critical Thinking",
  "Data Analysis",
  "Algorithm Design",
  "Machine Learning",
  "Artificial Intelligence",
  "Cloud Computing",
  "DevOps",
  "Agile Methodology",
  "Cybersecurity",
  "Network Architecture",
  "Database Management",
  "Big Data",
  "IoT (Internet of Things)",
  "UI/UX Design",
  "Product Management",
  "Project Management",
  "Data Visualization",
  "Statistical Analysis",
  "Version Control",
  "Continuous Integration",
  "Scrum",
  "Kanban",
  "Business Intelligence",
  "Natural Language Processing",
  "Robotics",
  "Digital Marketing",
  "Ethical Hacking",
  "Information Architecture",
  "User Research",
  "User-Centered Design",
  "User Interface Design",
  "User Experience Design",
  "System Architecture",
  "Mobile App Development",
  "Web Development",
  "API Design",
  "Test Automation",
  "Quality Assurance",
  "Parallel Computing",
  "Distributed Systems",
  "Containerization",
  "Microservices",
  "Virtual Reality",
  "Augmented Reality",
  "Blockchain",
  "Quantum Computing",
  "Data Engineering",
  "Data Science",
  "Business Analysis",
  "Risk Management",
  "Change Management",
  "IT Strategy",
  "Digital Transformation",
  "Leadership",
  "Time Management",
  "Communication Skills",
  "Cross-Functional Collaboration",
  "Strategic Thinking",
  "Decision Making",
  "Innovation",
  "Adaptability",
  "Troubleshooting",
  "Emotional Intelligence",
  "Crisis Management",
  "Vendor Management",
  "Ethical Leadership",
  "Remote Collaboration",
  "Cognitive Flexibility",
  "Stress Management",
  "Cultural Awareness",
  "Business Acumen",
  "Financial Literacy",
  "Data Privacy",
  "Compliance",
  "API Integration",
  "Frontend Development",
  "Backend Development",
  "Mobile UI Design",
  "Web UI Design",
  "Cloud Security",
  "Risk Assessment",
  "Incident Response",
  "Data Governance",
  "Predictive Analytics",
  "E-commerce",
  "Content Management",
  "Search Engine Optimization (SEO)",
  "User Acquisition",
  "Social Media Marketing",
  "Brand Strategy",
  "Content Strategy",
  "Technical Writing",
  "Presentation Skills",
  "Customer Relationship Management (CRM)",
  "Supply Chain Management",
  "Business Process Improvement",
  "Vendor Negotiation",
  "Data Warehousing",
  "Data Modeling",
  "Network Security",
  "Authentication and Authorization",
  "Data Ethics",
  "Change Leadership",
  "Code Refactoring",
  "Software Architecture",
  "Code Review",
  "Responsive Design",
  "Mobile Development",
  "Web Design",
  "Wireframing",
  "Prototyping",
  "Product Design",
  "Interaction Design",
  "Accessibility Design",
  "Database Administration",
  "ETL (Extract, Transform, Load)",
  "Database Optimization",
  "Network Administration",
  "Firewall Management",
  "IT Support",
  "Serverless Architecture",
  "Container Orchestration",
  "Infrastructure as Code",
  "Microservices Architecture",
  "Cloud Architecture",
  "Penetration Testing",
  "Vulnerability Assessment",
  "Threat Intelligence",
  "Intrusion Detection",
  "Identity and Access Management (IAM)",
  "Secure Software Development",
  "Secure Coding Practices",
  "Security Auditing",
  "Compliance Management",
  "IT Governance",
  "Technical Troubleshooting",
  "Root Cause Analysis",
  "Network Monitoring",
  "Performance Tuning",
  "Load Balancing",
  "Backup and Recovery",
  "API Development",
  "RESTful Services",
  "GraphQL",
  "Microservices Development",
  "Automated Testing",
  "Continuous Integration and Deployment (CI/CD)",
  "Scalability",
  "Reliability Engineering",
  "Monitoring and Alerting",
  "Version Control Systems",
  "Software Development Life Cycle (SDLC)",
  "Agile Development",
  "Pair Programming",
  "Test-Driven Development (TDD)",
  "Behavior-Driven Development (BDD)",
  "Team Leadership",
  "Agile Coaching",
  "Stakeholder Management",
  // and more...
];
