import React from "react";
import { FcDatabase } from "react-icons/fc";
import { SiOpenai } from "react-icons/si";
import {
  JavascriptOriginal,
  PythonOriginal,
  JavaOriginal,
  CsharpPlain,
  CplusplusPlain,
  RubyPlain,
  Html5Original,
  Css3Original,
  MicrosoftsqlserverPlain,
  MysqlOriginal,
  PostgresqlOriginal,
  SqliteOriginal,
  OracleOriginal,
  RedisOriginal,
  MongodbOriginal,
  TypescriptOriginal,
  BashOriginal,
  GitOriginal,
  GithubOriginal,
  COriginal,
  PhpOriginal,
  GoOriginalWordmark,
  RustPlain,
  KotlinOriginal,
  LuaOriginal,
  DartOriginal,
  SwiftOriginal,
  RPlain,
  DotNetOriginal,
  MatlabOriginal,
  ScalaOriginal,
  JuliaOriginal,
  FirebasePlain,
  Neo4jOriginal,
  AmazonwebservicesOriginal,
  AzurePlain,
  GooglecloudOriginal,
  DigitaloceanOriginal,
  HerokuOriginal,
  NodejsOriginal,
  ReactOriginal,
  JqueryOriginal,
  ExpressOriginal,
  AngularjsOriginal,
  NextjsOriginal,
  DotnetcorePlain,
  VuejsOriginal,
  WordpressPlain,
  FlaskOriginal,
  SpringOriginal,
  DjangoPlain,
  FastapiOriginal,
  LaravelPlain,
  SvelteOriginal,
  NumpyOriginal,
  PandasOriginal,
  TensorflowLine,
  FlutterOriginal,
  ApachekafkaOriginal,
  PytorchOriginal,
  OpencvOriginal,
  ElectronOriginal,
  XamarinOriginal,
  DockerOriginal,
  NpmOriginalWordmark,
  YarnOriginal,
  WebpackOriginal,
  KubernetesPlain,
  NugetOriginal,
  VscodeOriginal,
  IntellijOriginal,
  AndroidstudioOriginal,
  PycharmOriginal,
  JupyterOriginal,
  XcodeOriginal,
  WebstormOriginal,
  JiraOriginal,
  ConfluenceOriginal,
  MarkdownOriginal,
  TrelloPlain,
  TailwindcssPlain,
  Windows8Original,
  AndroidOriginal,
  UbuntuPlain,
  LinuxOriginal,
  ChromeOriginal,
  FigmaOriginal,
  UnityOriginal,
  RaspberrypiOriginal,
  ArduinoOriginal,
  PolygonPlain,
  SolidityOriginal,
  PrometheusOriginal,
  BlenderOriginal,
  MayaOriginal,
  OpenglPlain,
  D3jsOriginal,
  ReduxOriginal,
  GraphqlPlain,
  SocketioOriginal,
  ThreejsOriginal,
} from "devicons-react";

export const allIcons: { [name: string]: React.ReactNode } = {
  JavaScript: <JavascriptOriginal size={25} />,
  Python: <PythonOriginal size={25} />,
  Java: <JavaOriginal size={25} />,
  "C#": <CsharpPlain size={25} />,
  "C++": <CplusplusPlain size={25} />,
  Ruby: <RubyPlain size={25} />,
  HTML: <Html5Original size={25} />,
  CSS: <Css3Original size={25} />,
  SQL: <FcDatabase className="text-2xl" />,
  "Microsoft SQL Server": <MicrosoftsqlserverPlain size={25} />,
  MySQL: <MysqlOriginal size={25} />,
  PostgreSQL: <PostgresqlOriginal size={25} />,
  SQLite: <SqliteOriginal size={25} />,
  Oracle: <OracleOriginal size={25} />,
  Redis: <RedisOriginal size={25} />,
  MongoDB: <MongodbOriginal size={25} />,
  TypeScript: <TypescriptOriginal size={25} />,
  Bash: <BashOriginal size={25} />,
  Git: <GitOriginal size={25} />,
  GitHub: <GithubOriginal size={25} />,
  C: <COriginal size={25} />,
  PHP: <PhpOriginal size={25} />,
  Go: <GoOriginalWordmark size={25} />,
  Rust: <RustPlain size={25} />,
  Kotlin: <KotlinOriginal size={25} />,
  Lua: <LuaOriginal size={25} />,
  Dart: <DartOriginal size={25} />,
  Swift: <SwiftOriginal size={25} />,
  R: <RPlain size={25} />,
  ".NET": <DotNetOriginal size={25} />,
  MATLAB: <MatlabOriginal size={25} />,
  Scala: <ScalaOriginal size={25} />,
  Julia: <JuliaOriginal size={25} />,
  Firebase: <FirebasePlain size={25} />,
  Neo4j: <Neo4jOriginal size={25} />,
  AWS: <AmazonwebservicesOriginal size={25} />,
  Azure: <AzurePlain size={25} />,
  "Google Cloud": <GooglecloudOriginal size={25} />,
  DigitalOcean: <DigitaloceanOriginal size={25} />,
  Heroku: <HerokuOriginal size={25} />,
  "Three.js": <ThreejsOriginal size={25} />,
  "Node.js": <NodejsOriginal size={25} />,
  React: <ReactOriginal size={25} />,
  "React Native": <ReactOriginal size={25} />,
  jQuery: <JqueryOriginal size={25} />,
  "Express.js": <ExpressOriginal size={25} />,
  AngularJS: <AngularjsOriginal size={25} />,
  "Next.js": <NextjsOriginal size={25} />,
  ".NET Core": <DotnetcorePlain size={25} />,
  "Vue.js": <VuejsOriginal size={25} />,
  WordPress: <WordpressPlain size={25} />,
  Flask: <FlaskOriginal size={25} />,
  Spring: <SpringOriginal size={25} />,
  Django: <DjangoPlain size={25} />,
  FastAPI: <FastapiOriginal size={25} />,
  Laravel: <LaravelPlain size={25} />,
  Svelte: <SvelteOriginal size={25} />,
  NumPy: <NumpyOriginal size={25} />,
  Pandas: <PandasOriginal size={25} />,
  TensorFlow: <TensorflowLine size={25} />,
  Flutter: <FlutterOriginal size={25} />,
  "Apache Kafka": <ApachekafkaOriginal size={25} />,
  PyTorch: <PytorchOriginal size={25} />,
  ChatGPT: <SiOpenai className="text-2xl text-emerald-600" />,
  OpenCV: <OpencvOriginal size={25} />,
  Electron: <ElectronOriginal size={25} />,
  Xamarin: <XamarinOriginal size={25} />,
  Docker: <DockerOriginal size={25} />,
  npm: <NpmOriginalWordmark size={25} />,
  Yarn: <YarnOriginal size={25} />,
  Webpack: <WebpackOriginal size={25} />,
  Kubernetes: <KubernetesPlain size={25} />,
  NuGet: <NugetOriginal size={25} />,
  "VS Code": <VscodeOriginal size={25} />,
  "IntelliJ IDEA": <IntellijOriginal size={25} />,
  "Android Studio": <AndroidstudioOriginal size={25} />,
  PyCharm: <PycharmOriginal size={25} />,
  Jupyter: <JupyterOriginal size={25} />,
  Xcode: <XcodeOriginal size={25} />,
  WebStorm: <WebstormOriginal size={25} />,
  Jira: <JiraOriginal size={25} />,
  Confluence: <ConfluenceOriginal size={25} />,
  Markdown: <MarkdownOriginal size={25} />,
  Trello: <TrelloPlain size={25} />,
  "Tailwind CSS": <TailwindcssPlain size={25} />,
  Windows: <Windows8Original size={25} />,
  Android: <AndroidOriginal size={25} />,
  Ubuntu: <UbuntuPlain size={25} />,
  Linux: <LinuxOriginal size={25} />,
  Chrome: <ChromeOriginal size={25} />,
  Figma: <FigmaOriginal size={25} />,
  Unity: <UnityOriginal size={25} />,
  "Raspberry Pi": <RaspberrypiOriginal size={25} />,
  Arduino: <ArduinoOriginal size={25} />,
  Polygon: <PolygonPlain size={25} />,
  Solidity: <SolidityOriginal size={25} />,
  Prometheus: <PrometheusOriginal size={25} />,
  Blender: <BlenderOriginal size={25} />,
  Maya: <MayaOriginal size={25} />,
  OpenGL: <OpenglPlain size={25} />,
  "D3.js": <D3jsOriginal size={25} />,
  Redux: <ReduxOriginal size={25} />,
  GraphQL: <GraphqlPlain size={25} />,
  "Socket.IO": <SocketioOriginal size={25} />,
};
