import React from "react";
import { FcDatabase } from "react-icons/fc";
import {
  SiOpenai,
  SiMicrosoftaccess,
  SiMicrosoftexcel,
  SiMicrosoftpowerpoint,
  SiMicrosoftword,
  SiAmazonapigateway,
  SiAmazoncloudwatch,
  // SiAmazoncognito, // not defined
  SiAmazondocumentdb,
  SiAmazonec2,
  SiAmazonecs,
  // SiAmazonelasticache, // not defined
  SiAmazoniam,
  SiAmazonrds,
  SiAmazonredshift,
  SiAmazons3,
  SiAmazonsimpleemailservice,
  SiAmazonsqs,
  // SiAnthropic, // not defined
  SiArxiv,
  SiAuth0,
  SiAwsamplify,
  // SiAwselasticloadbalancing, // not defined
  SiAwsfargate,
  SiAwslambda,
  SiAzureartifacts,
  SiAzuredataexplorer,
  SiAzurefunctions,
  SiAzurepipelines,
  // SiClerk, // not defined
  SiDatabricks,
  SiDeepnote,
  SiExpo,
  SiGoogleanalytics,
  // SiGooglegemini, // not defined
  SiGooglebigquery,
  SiGooglecolab,
  // SiGooglecloudstorage, // not defined
  // SiGooglecloudspanner, // not defined
  SiGooglecloudcomposer,
  SiGoogleappsscript,
  SiGoogledatastudio,
  SiGoogledrive,
  SiGooglesheets,
  SiGoogleslides,
  SiHashicorp,
  SiHeadlessui,
  SiIbm,
  SiIbmcloud,
  SiIbmwatson,
  SiMdx,
  SiMicrosoftonedrive,
  SiRemix,
  SiRubyonrails,
  // SiShadcnui, // not defined
  SiSnowflake,
  SiStripe,
  SiWarp,
} from "react-icons/si";
import {
  JavascriptOriginal,
  PythonOriginal,
  JavaOriginal,
  CsharpPlain,
  CplusplusPlain,
  RubyPlain,
  Html5Original,
  Css3Original,
  MicrosoftsqlserverPlain,
  MysqlOriginal,
  PostgresqlOriginal,
  SqliteOriginal,
  OracleOriginal,
  RedisOriginal,
  MongodbOriginal,
  TypescriptOriginal,
  BashOriginal,
  GitOriginal,
  GithubOriginal,
  COriginal,
  PhpOriginal,
  GoOriginalWordmark,
  RustOriginal,
  KotlinOriginal,
  LuaOriginal,
  DartOriginal,
  SwiftOriginal,
  RPlain,
  DotNetOriginal,
  MatlabOriginal,
  ScalaOriginal,
  JuliaOriginal,
  FirebasePlain,
  Neo4jOriginal,
  AmazonwebservicesOriginalWordmark,
  AzureOriginal,
  GooglecloudOriginal,
  DigitaloceanOriginal,
  HerokuOriginal,
  NodejsOriginal,
  ReactOriginal,
  JqueryOriginal,
  ExpressOriginal,
  AngularOriginal,
  NextjsOriginal,
  DotnetcorePlain,
  VuejsOriginal,
  WordpressPlain,
  FlaskOriginal,
  SpringOriginal,
  DjangoPlain,
  FastapiOriginal,
  LaravelOriginal,
  SvelteOriginal,
  NumpyOriginal,
  PandasOriginal,
  TensorflowLine,
  FlutterOriginal,
  ApachekafkaOriginal,
  PytorchOriginal,
  OpencvOriginal,
  ElectronOriginal,
  XamarinOriginal,
  DockerOriginal,
  NpmOriginalWordmark,
  YarnOriginal,
  WebpackOriginal,
  KubernetesOriginal,
  NugetOriginal,
  VscodeOriginal,
  IntellijOriginal,
  AndroidstudioOriginal,
  PycharmOriginal,
  JupyterOriginal,
  XcodeOriginal,
  WebstormOriginal,
  JiraOriginal,
  ConfluenceOriginal,
  MarkdownOriginal,
  TrelloPlain,
  TailwindcssOriginal,
  Windows8Original,
  AndroidOriginal,
  UbuntuPlain,
  LinuxOriginal,
  ChromeOriginal,
  FigmaOriginal,
  UnityOriginal,
  RaspberrypiOriginal,
  ArduinoOriginal,
  PolygonPlain,
  SolidityOriginal,
  PrometheusOriginal,
  BlenderOriginal,
  MayaOriginal,
  OpenglPlain,
  D3jsOriginal,
  ReduxOriginal,
  GraphqlPlain,
  SocketioOriginal,
  ThreejsOriginal,
  AlgoliaOriginal,
  AlpinejsOriginal,
  AnacondaOriginal,
  AngularmaterialOriginal,
  AnsibleOriginal,
  AntdesignOriginal,
  ApacheairflowOriginal,
  ApachesparkOriginal,
  AppwriteOriginal,
  ArchlinuxOriginal,
  ArgocdOriginal,
  AstroOriginal,
  AtomOriginal,
  AxiosPlain,
  AzuredevopsOriginal,
  AzuresqldatabaseOriginal,
  BabelOriginal,
  BambooOriginal,
  BitbucketOriginal,
  BlazorOriginal,
  BootstrapOriginal,
  BrowserstackOriginal,
  BunOriginal,
  CakephpOriginal,
  CapacitorOriginal,
  CarbonOriginal,
  CassandraOriginal,
  CentosOriginal,
  ClarityOriginal,
  ClionOriginal,
  ClojureOriginal,
  CloudflareOriginal,
  CloudflareworkersOriginal,
  CmakeOriginal,
  CodepenOriginal,
  ConsulOriginal,
  ContaoOriginal,
  CorejsOriginal,
  CosmosdbOriginal,
  CouchbaseOriginal,
  CrystalOriginal,
  CypressioOriginal,
  DatagripOriginal,
  DataspellOriginal,
  DebianOriginal,
  DenojsOriginal,
  DiscordjsOriginal,
  DoctrineOriginal,
  DropwizardOriginal,
  DrupalOriginal,
  DynamodbOriginal,
  EclipseOriginal,
  ElasticsearchOriginal,
  EleventyOriginal,
  ElixirOriginal,
  EmbeddedcOriginal,
  EmberOriginal,
  EnvoyOriginal,
  EslintPlain,
  FaunadbOriginal,
  FedoraOriginal,
  FramermotionOriginal,
  GatsbyOriginal,
  GazeboOriginal,
  GithubactionsOriginal,
  GithubcodespacesOriginal,
  GitlabOriginal,
  GolandOriginal,
  GrpcPlain,
  HadoopOriginal,
  HardhatOriginal,
  HarvesterOriginal,
  HomebrewOriginal,
  InfluxdbOriginal,
  InsomniaPlain,
  IonicOriginal,
  JenkinsOriginal,
  JestPlain,
  JetpackcomposeOriginal,
  JiraalignOriginal,
  JsonOriginal,
  K3osOriginal,
  K3sOriginal,
  KaggleOriginal,
  KerasOriginal,
  MariadbOriginal,
  MaterialuiOriginal,
  MatplotlibOriginal,
  MochaOriginal,
  NeovimOriginal,
  NestjsOriginal,
  NetlifyOriginal,
  NetworkxOriginal,
  NginxOriginal,
  NodemonPlain,
  NotionOriginal,
  NuxtjsPlain,
  OauthOriginal,
  OktaPlain,
  OpenapiPlain,
  OpentelemetryOriginal,
  P5jsOriginal,
  PhotonengineOriginal,
  PlotlyOriginal,
  PnpmOriginal,
  PortainerOriginal,
  PostmanPlain,
  PowershellOriginal,
  PrismaOriginal,
  PypiOriginal,
  PyscriptOriginalWordmark,
  QuarkusOriginal,
  RealmOriginal,
  ReplitOriginal,
  RocksdbOriginal,
  RockylinuxOriginal,
  ScikitlearnOriginal,
  SeleniumOriginal,
  SolidjsOriginal,
  StreamlitOriginal,
  SupabaseOriginal,
  SwaggerOriginal,
  TerraformOriginal,
  TrpcPlain,
  VercelOriginal,
  VitejsOriginal,
  WasmOriginal,
  Web3Plain,
} from "devicons-react";

const allIcons: { [name: string]: React.ReactNode } = {
  JavaScript: <JavascriptOriginal size={25} />,
  Python: <PythonOriginal size={25} />,
  Java: <JavaOriginal size={25} />,
  "C#": <CsharpPlain size={25} />,
  "C++": <CplusplusPlain size={25} />,
  Ruby: <RubyPlain size={25} />,
  HTML: <Html5Original size={25} />,
  CSS: <Css3Original size={25} />,
  SQL: <FcDatabase className="text-2xl" />,
  "Microsoft SQL Server": <MicrosoftsqlserverPlain size={25} />,
  MySQL: <MysqlOriginal size={25} />,
  PostgreSQL: <PostgresqlOriginal size={25} />,
  SQLite: <SqliteOriginal size={25} />,
  Oracle: <OracleOriginal size={25} />,
  Redis: <RedisOriginal size={25} />,
  MongoDB: <MongodbOriginal size={25} />,
  TypeScript: <TypescriptOriginal size={25} />,
  Bash: <BashOriginal size={25} />,
  Git: <GitOriginal size={25} />,
  GitHub: <GithubOriginal size={25} />,
  C: <COriginal size={25} />,
  PHP: <PhpOriginal size={25} />,
  Go: <GoOriginalWordmark size={25} />,
  Rust: <RustOriginal size={25} color="orange" />,
  Kotlin: <KotlinOriginal size={25} />,
  Lua: <LuaOriginal size={25} />,
  Dart: <DartOriginal size={25} />,
  Swift: <SwiftOriginal size={25} />,
  R: <RPlain size={25} />,
  ".NET": <DotNetOriginal size={25} />,
  MATLAB: <MatlabOriginal size={25} />,
  Scala: <ScalaOriginal size={25} />,
  Julia: <JuliaOriginal size={25} />,
  Firebase: <FirebasePlain size={25} />,
  Supabase: <SupabaseOriginal size={25} />,
  Neo4j: <Neo4jOriginal size={25} />,
  AWS: <AmazonwebservicesOriginalWordmark size={25} />,
  Azure: <AzureOriginal size={25} />,
  "Google Cloud": <GooglecloudOriginal size={25} />,
  DigitalOcean: <DigitaloceanOriginal size={25} />,
  Heroku: <HerokuOriginal size={25} />,
  "Three.js": <ThreejsOriginal size={25} />,
  "Node.js": <NodejsOriginal size={25} />,
  React: <ReactOriginal size={25} />,
  "React Native": <ReactOriginal size={25} />,
  jQuery: <JqueryOriginal size={25} />,
  "Express.js": <ExpressOriginal size={25} />,
  AngularJS: <AngularOriginal size={25} />,
  "Next.js": <NextjsOriginal size={25} />,
  ".NET Core": <DotnetcorePlain size={25} />,
  "Vue.js": <VuejsOriginal size={25} />,
  WordPress: <WordpressPlain size={25} />,
  Flask: <FlaskOriginal size={25} />,
  Spring: <SpringOriginal size={25} />,
  Django: <DjangoPlain size={25} />,
  FastAPI: <FastapiOriginal size={25} />,
  Laravel: <LaravelOriginal size={25} />,
  "Microsoft Access": <SiMicrosoftaccess className="text-2xl text-red-700" />,
  Svelte: <SvelteOriginal size={25} />,
  NumPy: <NumpyOriginal size={25} />,
  Pandas: <PandasOriginal size={25} />,
  TensorFlow: <TensorflowLine size={25} />,
  Flutter: <FlutterOriginal size={25} />,
  "Apache Kafka": <ApachekafkaOriginal size={25} />,
  PyTorch: <PytorchOriginal size={25} />,
  ChatGPT: <SiOpenai className="text-2xl text-emerald-600" />,
  OpenCV: <OpencvOriginal size={25} />,
  Electron: <ElectronOriginal size={25} />,
  Xamarin: <XamarinOriginal size={25} />,
  Docker: <DockerOriginal size={25} />,
  npm: <NpmOriginalWordmark size={25} />,
  Yarn: <YarnOriginal size={25} />,
  Webpack: <WebpackOriginal size={25} />,
  Kubernetes: <KubernetesOriginal size={25} />,
  NuGet: <NugetOriginal size={25} />,
  "VS Code": <VscodeOriginal size={25} />,
  "IntelliJ IDEA": <IntellijOriginal size={25} />,
  "Android Studio": <AndroidstudioOriginal size={25} />,
  PyCharm: <PycharmOriginal size={25} />,
  Jupyter: <JupyterOriginal size={25} />,
  Xcode: <XcodeOriginal size={25} />,
  WebStorm: <WebstormOriginal size={25} />,
  Jira: <JiraOriginal size={25} />,
  Confluence: <ConfluenceOriginal size={25} />,
  Markdown: <MarkdownOriginal size={25} />,
  Trello: <TrelloPlain size={25} />,
  "Tailwind CSS": <TailwindcssOriginal size={25} />,
  Windows: <Windows8Original size={25} />,
  Android: <AndroidOriginal size={25} />,
  Ubuntu: <UbuntuPlain size={25} />,
  Linux: <LinuxOriginal size={25} />,
  Chrome: <ChromeOriginal size={25} />,
  Figma: <FigmaOriginal size={25} />,
  Unity: <UnityOriginal size={25} />,
  "Raspberry Pi": <RaspberrypiOriginal size={25} />,
  Arduino: <ArduinoOriginal size={25} />,
  Polygon: <PolygonPlain size={25} />,
  Solidity: <SolidityOriginal size={25} />,
  Prometheus: <PrometheusOriginal size={25} />,
  Blender: <BlenderOriginal size={25} />,
  Maya: <MayaOriginal size={25} />,
  OpenGL: <OpenglPlain size={25} />,
  "D3.js": <D3jsOriginal size={25} />,
  Redux: <ReduxOriginal size={25} />,
  GraphQL: <GraphqlPlain size={25} color="pink" />,
  "Socket.IO": <SocketioOriginal size={25} />,
  "Microsoft Word": <SiMicrosoftword className="text-2xl text-blue-600" />,
  "Microsoft Excel": <SiMicrosoftexcel className="text-2xl text-emerald-600" />,
  "Microsoft PowerPoint": (
    <SiMicrosoftpowerpoint className="text-2xl text-orange-500" />
  ),
  Algolia: <AlgoliaOriginal size={25} />,
  "Alpine.js": <AlpinejsOriginal size={25} />,
  Anaconda: <AnacondaOriginal size={25} />,
  "Angular Material": <AngularmaterialOriginal size={25} />,
  Ansible: <AnsibleOriginal size={25} />,
  "Ant Design": <AntdesignOriginal size={25} />,
  Airflow: <ApacheairflowOriginal size={25} />,
  Spark: <ApachesparkOriginal size={25} />,
  Appwrite: <AppwriteOriginal size={25} />,
  "Arch Linux": <ArchlinuxOriginal size={25} />,
  "Argo CD": <ArgocdOriginal size={25} />,
  Astro: <AstroOriginal size={25} />,
  Atom: <AtomOriginal size={25} />,
  Axios: <AxiosPlain size={25} />,
  Babel: <BabelOriginal size={25} />,
  Bamboo: <BambooOriginal size={25} />,
  Bitbucket: <BitbucketOriginal size={25} />,
  Blazor: <BlazorOriginal size={25} />,
  Bootstrap: <BootstrapOriginal size={25} />,
  BrowserStack: <BrowserstackOriginal size={25} />,
  Bun: <BunOriginal size={25} />,
  CakePHP: <CakephpOriginal size={25} />,
  Capacitor: <CapacitorOriginal size={25} />,
  Carbon: <CarbonOriginal size={25} />,
  Cassandra: <CassandraOriginal size={25} />,
  CentOS: <CentosOriginal size={25} />,
  Clarity: <ClarityOriginal size={25} />,
  CLion: <ClionOriginal size={25} />,
  Clojure: <ClojureOriginal size={25} />,
  Cloudflare: <CloudflareOriginal size={25} />,
  "Cloudfare Workers": <CloudflareworkersOriginal size={25} />,
  CMake: <CmakeOriginal size={25} />,
  Codepen: <CodepenOriginal size={25} />,
  Consul: <ConsulOriginal size={25} />,
  Contao: <ContaoOriginal size={25} />,
  "Core-js": <CorejsOriginal size={25} />,
  "Azure DevOps": <AzuredevopsOriginal size={25} />,
  "Azure SQL Database": <AzuresqldatabaseOriginal size={25} />,
  CosmosDB: <CosmosdbOriginal size={25} />,
  Couchbase: <CouchbaseOriginal size={25} />,
  Crystal: <CrystalOriginal size={25} />,
  Cypress: <CypressioOriginal size={25} />,
  DataGrip: <DatagripOriginal size={25} />,
  DataSpell: <DataspellOriginal size={25} />,
  Debian: <DebianOriginal size={25} />,
  Deno: <DenojsOriginal size={25} />,
  "discord.js": <DiscordjsOriginal size={25} />,
  Doctrine: <DoctrineOriginal size={25} />,
  Dropwizard: <DropwizardOriginal size={25} />,
  Drupal: <DrupalOriginal size={25} />,
  DynamoDB: <DynamodbOriginal size={25} />,
  Eclipse: <EclipseOriginal size={25} />,
  Elasticsearch: <ElasticsearchOriginal size={25} />,
  Eleventy: <EleventyOriginal size={25} />,
  Elixir: <ElixirOriginal size={25} />,
  "Embedded C": <EmbeddedcOriginal size={25} color="blue" />,
  Ember: <EmberOriginal size={25} />,
  Envoy: <EnvoyOriginal size={25} />,
  ESLint: <EslintPlain size={25} />,
  FaunaDB: <FaunadbOriginal size={25} />,
  Fedora: <FedoraOriginal size={25} />,
  "Framer Motion": <FramermotionOriginal size={25} />,
  Gatsby: <GatsbyOriginal size={25} />,
  Gazebo: <GazeboOriginal size={25} />,
  "GitHub Action": <GithubactionsOriginal size={25} />,
  "GitHub Codespaces": <GithubcodespacesOriginal size={25} />,
  GitLab: <GitlabOriginal size={25} />,
  GoLand: <GolandOriginal size={25} />,
  gRPC: <GrpcPlain size={25} />,
  Hadoop: <HadoopOriginal size={25} />,
  Hardhat: <HardhatOriginal size={25} />,
  Harvester: <HarvesterOriginal size={25} />,
  Homebrew: <HomebrewOriginal size={25} />,
  InfluxDB: <InfluxdbOriginal size={25} />,
  Insomnia: <InsomniaPlain size={25} />,
  Ionic: <IonicOriginal size={25} />,
  Jenkins: <JenkinsOriginal size={25} />,
  Jest: <JestPlain size={25} />,
  "Jetpack Compose": <JetpackcomposeOriginal size={25} />,
  "Jira Align": <JiraalignOriginal size={25} />,
  JSON: <JsonOriginal size={25} />,
  K3OS: <K3osOriginal size={25} />,
  K3s: <K3sOriginal size={25} />,
  Kaggle: <KaggleOriginal size={25} />,
  Keras: <KerasOriginal size={25} />,
  MariaDB: <MariadbOriginal size={25} />,
  "Material UI": <MaterialuiOriginal size={25} />,
  Matplotlib: <MatplotlibOriginal size={25} />,
  Mocha: <MochaOriginal size={25} />,
  Neovim: <NeovimOriginal size={25} />,
  NestJS: <NestjsOriginal size={25} />,
  Netlify: <NetlifyOriginal size={25} />,
  NetworkX: <NetworkxOriginal size={25} />,
  NGINX: <NginxOriginal size={25} />,
  Nodemon: <NodemonPlain size={25} />,
  Notion: <NotionOriginal size={25} />,
  Nuxt: <NuxtjsPlain size={25} />,
  OAuth: <OauthOriginal size={25} />,
  Okta: <OktaPlain size={25} />,
  OpenAPI: <OpenapiPlain size={25} />,
  OpenTelemetry: <OpentelemetryOriginal size={25} />,
  "p5.js": <P5jsOriginal size={25} />,
  "Photon Engine": <PhotonengineOriginal size={25} />,
  Plotly: <PlotlyOriginal size={25} />,
  pnpm: <PnpmOriginal size={25} />,
  Portainer: <PortainerOriginal size={25} />,
  Postman: <PostmanPlain size={25} />,
  Powershell: <PowershellOriginal size={25} />,
  Prisma: <PrismaOriginal size={25} />,
  PyPI: <PypiOriginal size={25} />,
  PyScript: <PyscriptOriginalWordmark size={25} />,
  Quarkus: <QuarkusOriginal size={25} />,
  Realm: <RealmOriginal size={25} />,
  Replit: <ReplitOriginal size={25} />,
  RocksDB: <RocksdbOriginal size={25} />,
  "Rocky Linux": <RockylinuxOriginal size={25} />,
  "scikit-learn": <ScikitlearnOriginal size={25} />,
  Selenium: <SeleniumOriginal size={25} color="green" />,
  "Solid.js": <SolidjsOriginal size={25} />,
  Streamlit: <StreamlitOriginal size={25} />,
  Swagger: <SwaggerOriginal size={25} />,
  Terraform: <TerraformOriginal size={25} />,
  tRPC: <TrpcPlain size={25} />,
  Vercel: <VercelOriginal size={25} />,
  Vite: <VitejsOriginal size={25} />,
  WebAssembly: <WasmOriginal size={25} />,
  "Web3.js": <Web3Plain size={25} />,
  "Amazon API Gateway": (
    <SiAmazonapigateway className="text-2xl text-purple-500" />
  ),
  "Amazon Cloudwatch": (
    <SiAmazoncloudwatch className="text-2xl text-pink-500" />
  ),
  // "Amazon Cognito": <SiAmazoncognito className="text-2xl text-red-500" />,
  "Amazon DocumentDB": (
    <SiAmazondocumentdb className="text-2xl text-purple-600" />
  ),
  "Amazon EC2": <SiAmazonec2 className="text-2xl text-orange-500" />,
  "Amazon ECS": <SiAmazonecs className="text-2xl text-orange-500" />,
  // "Amazon ElasticCache": (
  //   <SiAmazonelasticache className="text-2xl text-blue-500" />
  // ),
  "AWS IAM": <SiAmazoniam className="text-2xl text-red-500" />,
  "Amazon RDS": <SiAmazonrds className="text-2xl text-blue-500" />,
  "Amazon Redshift": <SiAmazonredshift className="text-2xl text-blue-500" />,
  "Amazon S3": <SiAmazons3 className="text-2xl text-red-500" />,
  "Amazon SES": (
    <SiAmazonsimpleemailservice className="text-2xl text-amber-400" />
  ),
  "Amazon SQS": <SiAmazonsqs className="text-2xl text-amber-400" />,
  // Claude: <SiAnthropic className="text-2xl text-black" />,
  ArXiv: <SiArxiv className="text-2xl" />,
  Auth0: <SiAuth0 className="text-2xl" />,
  "AWS Amplify": <SiAwsamplify className="text-2xl text-orange-300" />,
  // "AWS ELB": <SiAwselasticloadbalancing className="text-2xl text-purple-500" />,
  "AWS Fargate": <SiAwsfargate className="text-2xl text-orange-500" />,
  "AWS Lambda": <SiAwslambda className="text-2xl text-orange-500" />,
  "Azure Artifacts": <SiAzureartifacts className="text-2xl text-pink-500" />,
  "Azure Data Explorer": (
    <SiAzuredataexplorer className="text-2xl text-sky-400" />
  ),
  "Azure Functions": <SiAzurefunctions className="text-2xl text-sky-400" />,
  "Azure Pipelines": <SiAzurepipelines className="text-2xl text-blue-700" />,
  // Clerk: <SiClerk className="text-2xl text-violet-500" />,
  Databricks: <SiDatabricks className="text-2xl text-orange-600" />,
  Deepnote: <SiDeepnote className="text-2xl text-blue-600" />,
  Expo: <SiExpo className="text-2xl text-black" />,
  "Google Analytics": (
    <SiGoogleanalytics className="text-2xl text-orange-400" />
  ),
  // Gemini: <SiGooglegemini className="text-2xl text-purple-300" />,
  "Google BigQuery": <SiGooglebigquery className="text-2xl text-blue-500" />,
  "Google Colab": <SiGooglecolab className="text-2xl text-orange-400" />,
  // "Google Cloud Storage": (
  //   <SiGooglecloudstorage className="text-2xl text-blue-500" />
  // ),
  "Google Cloud Composer": (
    <SiGooglecloudcomposer className="text-2xl text-blue-500" />
  ),
  // "Google Cloud Spanner": (
  //   <SiGooglecloudspanner className="text-2xl text-blue-500" />
  // ),
  "Google Apps Script": (
    <SiGoogleappsscript className="text-2xl text-green-500" />
  ),
  "Google Data Studio": (
    <SiGoogledatastudio className="text-2xl text-blue-500" />
  ),
  "Google Drive": <SiGoogledrive className="text-2xl text-yellow-500" />,
  "Google Slides": <SiGoogleslides className="text-2xl text-yellow-500" />,
  "Google Sheets": <SiGooglesheets className="text-2xl text-green-500" />,
  Hashicorp: <SiHashicorp className="text-2xl text-black" />,
  "Headless UI": <SiHeadlessui className="text-2xl text-sky-400" />,
  IBM: <SiIbm className="text-2xl text-blue-700" />,
  "IBM Cloud": <SiIbmcloud className="text-2xl text-sky-400" />,
  "IBM WatsonX": <SiIbmwatson className="text-2xl text-blue-700" />,
  MDX: <SiMdx className="text-2xl text-black" />,
  "Microsoft OneDrive": (
    <SiMicrosoftonedrive className="text-2xl text-blue-600" />
  ),
  Remix: <SiRemix className="text-2xl text-sky-400" />,
  "Ruby on Rails": <SiRubyonrails className="text-2xl text-red-600" />,
  // "Shadcn UI": <SiShadcnui className="text-2xl text-black" />,
  Snowflake: <SiSnowflake className="text-2xl text-sky-500" />,
  Stripe: <SiStripe className="text-2xl text-purple-500" />,
  Warp: <SiWarp className="text-2xl text-sky-400" />,
};

/*
    SiAmazoncognito, // not defined
  SiAmazondocumentdb,
  SiAmazonec2,
  SiAmazonecs,
  SiAmazonelasticache, // not defined
  SiAmazoniam,
  SiAmazonrds,
  SiAmazonredshift,
  SiAmazons3,
  SiAmazonsimpleemailservice,
  SiAmazonsqs,
  SiAnthropic, // not defined
  SiArxiv,
  SiAuth0,
  SiAwsamplify,
  SiAwselasticloadbalancing, // not defined
  SiAwsfargate,
  SiAwslambda,
  SiAzureartifacts,
  SiAzuredataexplorer,
  SiAzurefunctions,
  SiAzurepipelines,
  SiClerk, // not defined
  SiDatabricks,
  SiDeepnote,
  SiExpo,
  SiGoogleanalytics,
  SiGooglegemini, // not defined
  SiGooglebigquery,
  SiGooglecolab,
  SiGooglecloudstorage, // not defined
  SiGooglecloudspanner, // not defined
  SiGooglecloudcomposer,
  SiGoogleappsscript,
  SiGoogledatastudio,
  SiGoogledrive,
  SiGooglesheets,
  SiGoogleslides,
  SiHashicorp,
  SiHeadlessui,
  SiIbm,
  SiIbmcloud,
  SiIbmwatson,
  SiMdx,
  SiMicrosoftonedrive,
  SiRemix,
  SiRubyonrails,
  SiShadcnui, // not defined
  SiSnowflake,
  SiStripe,
  SiWarp,
*/

// Create an array of sorted keys
const sortedKeys = Object.keys(allIcons).sort();

// Create a new object with sorted keys and their corresponding values
const sortedIcons: { [name: string]: React.ReactNode } = {};
sortedKeys.forEach((key) => {
  sortedIcons[key] = allIcons[key];
});

// Now sortedIcons contains the alphabetically sorted object
export default sortedIcons;
